name: Update python source
on:
  push:
    branches:
      - main
    paths:
      - python/**
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd python/src
          zip -r ../../source.zip .
          cd ../..
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - run: aws s3 cp source.zip s3://reizt-lambda-efs-sqlite/python/source.zip
