name: Update python source
on:
  push:
    branches:
      - main
    paths:
      - python/**
      - .github/workflows/python-source.yml
      - .github/actions/update-source/action.yml
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    env:
      artifact: source.zip
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd src
          zip -r ../${{ env.artifact }} .
          cd ..
      - uses: ./.github/actions/update-source
        with:
          aws-role-arn: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          artifact: python/${{ env.artifact }}
          lambda: les-python
          bucket: reizt-lambda-efs-sqlite
          key: python/source.zip
