name: Update python source
on:
  push:
    branches:
      - main
    paths:
      - python/**
      - .github/workflows/python-source.yml
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
env:
  artifact: source.zip
  function: les-python
  bucket: reizt-lambda-efs-sqlite
  key: python/source.zip
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd python/src
          zip -r ../../${{ env.artifact }} .
          cd ../..
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - run: aws s3 cp ${{ env.artifact }} s3://${{ env.bucket }}/${{ env.key }}
      - id: get-object-version
        run: |
          echo "version=$(aws s3api list-object-versions \
            --bucket ${{ env.bucket }} \
            --prefix ${{ env.key }} \
            --query 'Versions[0].VersionId' \
            --output text)" >> $GITHUB_OUTPUT
      - run: |
          aws lambda update-function-code \
            --function-name ${{ env.function }} \
            --s3-bucket ${{ env.bucket }} \
            --s3-key ${{ env.key }} \
            --s3-object-version ${{ steps.get-object-version.outputs.version }}
